# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install build dependencies
RUN pip install --upgrade pip

# Copy source code
COPY . /app

# Install package without running scripts (if any)
RUN pip install .

# Expose port if needed by Blender addon, though MCP server communicates via stdio
# EXPOSE 9876

# Command to run the MCP server
CMD ["blender-mcp", "--stdio"]
